Cleanup publish
duffelhq/duffel-components pull request #118
Opened 2023-06-12 15:19 UTC by igorp1

__What__

This PR makes a few changes around our build setup and documentation to make sure that the component library is published to npm successfully. I've pushed a few versions with the `canary` suffix and have tested on duffelhq/hq to make sure we are able to consume the package as expected. You can see the tests below:

1. Using custom element 

https://github.com/duffelhq/duffel-components/assets/2934495/5791e65b-fa12-47a3-9851-3452ed9523d1

2. Using react component

https://github.com/duffelhq/duffel-components/assets/2934495/f871bd74-b166-45bd-95c4-7eaf3199b8ef

2023-06-13 13:23 UTC, shaundon requested changes

2023-06-13 13:23 UTC, shaundon commented on CONTRIBUTING.md
> +## Debug mode
```suggestion
# Guide for contributors

This guide is aimed at people who want to **contribute** to this codebase (e.g. run it locally, change things, and so on). For instructions on how to **use** the components on your own website, see [README.md](/README.md).


## Debug mode
```

2023-06-13 16:10 UTC, igorp1 commented on CONTRIBUTING.md
> +### Setup environment
Ahh true, fixed it!

2023-06-13 16:11 UTC, igorp1 commented on CONTRIBUTING.md
> +## Debug mode
Good catch, updated!

2023-06-14 07:52 UTC, shaundon approved these changes

2023-06-14 11:36 UTC, merged